import assert from 'node:assert/strict'
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { test } from 'node:test'
import { setTimeout as delay } from 'node:timers/promises'
import { sourceSnapshot, watchSources } from '../../scripts/profile/dev-watch.mjs'

async function until(predicate: () => boolean) {
  for (let i = 0; i < 100; i++) {
    if (predicate()) return
    await delay(30)
  }
  assert.ok(predicate(), 'watcher did not reach the expected state')
}

test('watcher serializes edits, keeps running after build failure, and separates Client from Host updates', async t => {
  const root = await mkdtemp(join(tmpdir(), 'nook-watch-test-'))
  const controller = new AbortController()
  await mkdir(resolve(root, 'packages/ui/src/client'), { recursive: true })
  await mkdir(resolve(root, 'packages/ui/lib'), { recursive: true })
  const client = resolve(root, 'packages/ui/src/client/index.tsx')
  await writeFile(client, 'first')
  await writeFile(resolve(root, 'packages/ui/lib/index.js'), 'export const name = "ui"')
  let builds = 0
  let restarts = 0
  let rejectBuild = false
  let release: (() => void) | undefined
  const messages: string[] = []
  const watching = watchSources({
    root,
    initial: await sourceSnapshot(root),
    signal: controller.signal,
    report: (message: string) => messages.push(message),
    build: async () => {
      builds++
      if (rejectBuild) throw new Error('invalid source')
      if (builds === 2)
        await new Promise<void>(resolve => {
          release = resolve
        })
    },
    restart: async () => {
      restarts++
    },
  })
  t.after(async () => {
    controller.abort()
    release?.()
    await watching
    await rm(root, { recursive: true, force: true })
  })
  await writeFile(client, 'second')
  await until(() => messages.includes('[nook dev] Client updated.'))
  assert.equal(restarts, 0)
  await mkdir(resolve(root, 'packages/ui/python/__pycache__'), { recursive: true })
  await writeFile(resolve(root, 'packages/ui/python/__pycache__/collector.pyc'), 'generated by a runtime request')
  await delay(400)
  assert.equal(builds, 1, 'running a Python provider must not trigger a source rebuild')
  await writeFile(client, 'third')
  await until(() => release !== undefined)
  await writeFile(client, 'fourth, saved while build was running')
  release?.()
  await until(() => builds === 3)
  assert.equal(restarts, 0)
  rejectBuild = true
  await writeFile(client, 'invalid')
  await until(() => messages.some(message => message.includes('invalid source')))
  assert.equal(restarts, 0)
  rejectBuild = false
  await writeFile(resolve(root, 'packages/ui/src/index.ts'), 'host edit')
  await until(() => restarts === 1)
  controller.abort()
  await watching
  const count = builds
  await writeFile(client, 'after shutdown')
  await delay(350)
  assert.equal(builds, count)
})
